import { readdir, readFile } from 'node:fs/promises'
import path from 'node:path'

const rootDir = process.cwd()
const verbsDir = path.join(rootDir, 'src/data/verbs')
const minRank = Number(process.env.MIN_RANK ?? 3001)
const maxRank = Number(process.env.MAX_RANK ?? 5000)

const placeholderExamplePatterns = [
  /^Uczę się, jak poprawnie /i,
  /^I am learning how to correctly /i,
  /^Я вчуся, як правильно /i,
]

const fallbackNotePatterns = [
  /fallback/i,
  /generated by fallback/i,
  /needs review/i,
  /should be checked/i,
]

function clean(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function normalize(value) {
  return clean(value).toLocaleLowerCase('pl-PL')
}

function collectForms(verb) {
  const forms = new Set([normalize(verb.infinitive)])
  Object.values(verb.forms?.present ?? {}).forEach((value) => forms.add(normalize(value)))
  const past = verb.forms?.past ?? {}
  Object.values(past).forEach((entry) => {
    Object.values(entry ?? {}).forEach((value) => forms.add(normalize(value)))
  })
  forms.delete('')
  return forms
}

function hasDuplicate(values) {
  const seen = new Set()
  for (const value of values.map(normalize).filter(Boolean)) {
    if (seen.has(value)) {
      return true
    }
    seen.add(value)
  }
  return false
}

function exampleContainsKnownForm(verb, example) {
  const text = normalize(example?.pl)
  if (!text) {
    return false
  }
  return [...collectForms(verb)].some((form) => {
    if (form.length < 3) {
      return text === form || text.includes(` ${form} `)
    }
    return text.includes(form)
  })
}

async function loadVerbs() {
  const files = (await readdir(verbsDir)).filter((file) => file.endsWith('.json')).sort()
  const verbs = []
  for (const file of files) {
    verbs.push(...JSON.parse(await readFile(path.join(verbsDir, file), 'utf8')))
  }
  return verbs
}

function addIssue(issues, code, verb, detail) {
  issues.push({
    code,
    rank: verb.frequencyRank,
    id: verb.id,
    infinitive: verb.infinitive,
    detail,
  })
}

function auditVerb(verb, issues) {
  if (verb.reviewStatus === 'fallback-needs-review') {
    addIssue(issues, 'fallback-review-status', verb, 'Record is still marked as fallback-needs-review.')
  }

  if (verb.aspect === 'unknown') {
    addIssue(issues, 'unknown-aspect', verb, 'Aspect is unknown.')
  }

  if (!Array.isArray(verb.sourceUrls) || verb.sourceUrls.length === 0) {
    addIssue(issues, 'missing-source-url', verb, 'No source URLs are recorded.')
  }

  if (verb.notes?.some((note) => fallbackNotePatterns.some((pattern) => pattern.test(note)))) {
    addIssue(issues, 'fallback-note', verb, 'Notes indicate generated fallback data or review-needed data.')
  }

  if (hasDuplicate(verb.translations?.en ?? [])) {
    addIssue(issues, 'duplicate-english-translation', verb, 'English translations contain duplicates.')
  }

  if (hasDuplicate(verb.translations?.uk ?? [])) {
    addIssue(issues, 'duplicate-ukrainian-translation', verb, 'Ukrainian translations contain duplicates.')
  }

  if ((verb.translations?.en ?? []).some((value) => clean(value).length > 120)) {
    addIssue(issues, 'long-english-translation', verb, 'English translation is suspiciously long.')
  }

  if ((verb.translations?.uk ?? []).some((value) => clean(value).length > 120)) {
    addIssue(issues, 'long-ukrainian-translation', verb, 'Ukrainian translation is suspiciously long.')
  }

  if (hasDuplicate((verb.examples ?? []).map((example) => example.pl))) {
    addIssue(issues, 'duplicate-polish-example', verb, 'Polish examples contain duplicates.')
  }

  for (const example of verb.examples ?? []) {
    const fields = [example.pl, example.en, example.uk].map(clean)
    if (fields.some((value) => !value)) {
      addIssue(issues, 'empty-example-field', verb, 'Example has an empty Polish, English, or Ukrainian field.')
    }
    if (fields.some((value) => value.length > 180)) {
      addIssue(issues, 'long-example', verb, 'Example is suspiciously long.')
    }
    if (fields.some((value) => placeholderExamplePatterns.some((pattern) => pattern.test(value)))) {
      addIssue(issues, 'placeholder-example', verb, 'Example uses a generator placeholder template.')
    }
    if (!exampleContainsKnownForm(verb, example)) {
      addIssue(issues, 'example-without-known-form', verb, 'Polish example does not contain the infinitive or a known generated form.')
    }
  }
}

async function main() {
  const verbs = (await loadVerbs()).filter((verb) => verb.frequencyRank >= minRank && verb.frequencyRank <= maxRank)
  if (!verbs.length) {
    throw new Error(`No verbs found in audit range ${minRank}-${maxRank}.`)
  }

  const issues = []
  verbs.forEach((verb) => auditVerb(verb, issues))

  if (issues.length) {
    console.error(`Verb audit found ${issues.length} issue(s) in ranks ${minRank}-${maxRank}.`)
    const grouped = new Map()
    issues.forEach((issue) => {
      grouped.set(issue.code, [...(grouped.get(issue.code) ?? []), issue])
    })
    for (const [code, group] of grouped) {
      console.error(`\n${code}: ${group.length}`)
      group.slice(0, 25).forEach((issue) => {
        console.error(`  #${issue.rank} ${issue.id}: ${issue.detail}`)
      })
      if (group.length > 25) {
        console.error(`  ... ${group.length - 25} more`)
      }
    }
    process.exit(1)
  }

  console.log(`Audited ${verbs.length} verbs in ranks ${minRank}-${maxRank}; no blocking issues found.`)
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
